-- DROP SCHEMA public;

--CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE address_id_seq;

CREATE SEQUENCE address_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE building_id_seq;

CREATE SEQUENCE building_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE main_address_id_seq;

CREATE SEQUENCE main_address_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE person_id_seq;

CREATE SEQUENCE person_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE zip_id_seq;

CREATE SEQUENCE zip_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.address definition

-- Drop table

-- DROP TABLE address;

CREATE TABLE address (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	secondary_person_id int8 NOT NULL,
	city varchar(255) NULL,
	state varchar(255) NULL,
	street varchar(255) NULL,
	CONSTRAINT address_pkey PRIMARY KEY (id)
);


-- public.main_address definition

-- Drop table

-- DROP TABLE main_address;

CREATE TABLE main_address (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city varchar(255) NULL,
	state varchar(255) NULL,
	street varchar(255) NULL,
	CONSTRAINT main_address_pkey PRIMARY KEY (id)
);


-- public.zip definition

-- Drop table

-- DROP TABLE zip;

CREATE TABLE zip (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	zip varchar(255) NULL,
	CONSTRAINT zip_pkey PRIMARY KEY (id)
);


-- public.building definition

-- Drop table

-- DROP TABLE building;

CREATE TABLE building (
	address_id int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT building_address_id_key UNIQUE (address_id),
	CONSTRAINT building_pkey PRIMARY KEY (id),
	CONSTRAINT fk4rktkpvfspkuvbq6bgswkrxdo FOREIGN KEY (address_id) REFERENCES main_address(id)
);


-- public.person definition

-- Drop table

-- DROP TABLE person;

CREATE TABLE person (
	age int4 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	main_address_id int8 NULL,
	gender varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT person_main_address_id_key UNIQUE (main_address_id),
	CONSTRAINT person_pkey PRIMARY KEY (id),
	CONSTRAINT fkm9fk86whfd48o1e3qiy35j9cp FOREIGN KEY (main_address_id) REFERENCES main_address(id)
);


-- public.secondary_address definition

-- Drop table

-- DROP TABLE secondary_address;

CREATE TABLE secondary_address (
	id int8 NOT NULL,
	secondary_person_id int8 NOT NULL,
	CONSTRAINT secondary_address_pkey PRIMARY KEY (id),
	CONSTRAINT fk292bihq7rryvs3tk9ue22tse4 FOREIGN KEY (id) REFERENCES main_address(id),
	CONSTRAINT fk8w6k3n1p8ukaf7wwahjxbermp FOREIGN KEY (secondary_person_id) REFERENCES person(id)
);